# Generated by Django 2.2.3 on 2020-06-24 06:44

from django.db import migrations, models
from django.contrib.auth import get_user_model


def create_user(apps, schema_editor):
    User = get_user_model()
    for i in range(1, 10):
        User.objects.create(
            username = f"username_{i}",
            first_name = f"first_{i}",
            last_name = f"last_{i}",
            email = f"username_{i}@example.com"
        )

def insert_dummy(apps, schema_editor):
    Post = apps.get_model("post", "Post")

    for i in range(1, 100):
        Post.objects.create(title=f"title {i}",
                            body="Lorem ipsum dolor sit amet, consectetur "
                                 "adipiscing elit, sed do eiusmod tempor "
                                 "incididunt ut labore et dolore magna aliqua.",
                            is_show=True,
                            user_id=int( (i % 9) +1)
                            )


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user),
        migrations.RunPython(insert_dummy),

    ]
